# Generated by Django 4.2.4 on 2023-08-21 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='recipeingredient',
            name='unique ingredient',
        ),
    ]
