# Generated by Django 4.2.3 on 2023-08-30 11:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_recipeshoppinglist_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Время не менее 1 минуты!'), django.core.validators.MaxValueValidator(480, message='Время приготовления не более 8 часов!')], verbose_name='Время приготовления'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Укажите количество не меньше 1!'), django.core.validators.MaxValueValidator(5000, message='Укажите количество не более 5000!')], verbose_name='Количество единиц ингредиента'),
        ),
    ]
