---
name: Forget pass

on:
  push:
    branches: [ master ]

jobs:
  send_message:
    runs-on: ubuntu-latest
    steps:
    - name: send message
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: ${{ secrets.USERNAME }}
...
